# NOTE : foilix uses libra that is py3 only
# yet, an optimization will run under py2
sudo: required

git:
  depth: 3

services:
  - docker

install:
  - docker build --file Dockerfile.py3 --tag guillaume-florent/foilix-py3:latest .

script:
  - docker run guillaume-florent/foilix-py3:latest /bin/bash -c "cd /opt/foilix;pytest tests/"

after_script:
  - docker images