language: python
sudo: required

# Ubuntu 14.04 LTS Server Edition 64 bit
dist: trusty

python:
  - "2.7"
  # pyside support only up to 3.2, conda defaults to 3.4 -> no python3.* support

# Setup anaconda
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib pyside
  - pip install -r requirements.txt
  - pip install python-coveralls
  - pip install coverage
  - pip install nose
  - python setup.py install

script:
  - nosetests --with-coverage

after_success:
  coveralls --config_file .coveragerc


